export const ADD_SURVEY = 'ADD_SURVEY';
export const DELETE_SURVEY = 'DELETE_SURVEY';
export const ADD_RESPONSE = 'ADD_RESPONSE';
export const DELETE_RESPONSE = 'DELETE_RESPONSE';
export const TOGGLE_FORM = 'TOGGLE_FORM';